spring:
  application:
    name: user-service
  main:
    show-banner: false
  server:
    port: ${SERVER_PORT:8084}
  datasource:
    url: ${SPRING_DATASOURCE_URL_USERSDB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        default_schema: users_db
        format_sql: true
        use_sql_comments: true
  security:
    user:
      name: ${SECURITY_USER_NAME:user}
      password: ${SECURITY_USER_PASSWORD:password}
debug: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql: trace

springdoc:
  swagger-ui:
    use-root-path: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL}
