version: "3.8"

x-common-env:
  &common-env #env_file: .env.dev # Uncomment this and comment the one bellow to use production profile.
  env_file: .env.prod #Uncomment this and comment the one above to use production profile.

services:
  eureka-server:
    <<: *common-env
    build:
      context: ./eureka-server
      dockerfile: src/main/docker/Dockerfile
    image: docisjp/eureka-server:latest
    restart: always
    ports:
      - "8761:8761"
    networks:
      - backend-network

  user-service:
    <<: *common-env
    build:
      context: ./user-service
      dockerfile: src/main/docker/Dockerfile
    image: docisjp/user-service:latest
    restart: always
    ports:
      - "8084:8084"
    depends_on:
      - eureka-server
      - shopswiftly_db
    networks:
      - backend-network

  shopswiftly_db:
    <<: *common-env
    image: "postgres:latest"
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./initdb/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    networks:
      - backend-network

  product-service:
    <<: *common-env
    build:
      context: ./product-service
      dockerfile: src/main/docker/Dockerfile
    image: docisjp/product-service:latest
    restart: always
    ports:
      - "8086:8086"
    depends_on:
      - eureka-server
      - shopswiftly_db
    networks:
      - backend-network

  transaction-service:
    <<: *common-env
    build:
      context: ./transaction-service
      dockerfile: src/main/docker/Dockerfile
    image: docisjp/transaction-service:latest
    restart: always
    ports:
      - "8085:8085"
    depends_on:
      - eureka-server
      - shopswiftly_db
    networks:
      - backend-network

  api-gateway:
    <<: *common-env
    build:
      context: ./api-gateway
      dockerfile: src/main/docker/Dockerfile
    image: docisjp/api-gateway:latest
    restart: always
    ports:
      - "8083:8083"
    depends_on:
      - eureka-server
      - shopswiftly_db
      - user-service
    networks:
      - backend-network

volumes:
  postgres_data:

networks:
  backend-network:
    driver: bridge
